name: Build and Push Docker Image

on:
  push:
    branches:
      - conex-api-steam

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: push image to docker hub
        run: |
          docker login -u josepguiusilles -p ${{ secrets.P_DOC }} 

      - name: build image
        run: docker build -t josepguiusilles/devops-qr-code-backend:latest .

      - name: Push image
        run: docker push josepguiusilles/devops-qr-code-backend:latest